/*
    Attention: This file is generated by "dot-i18n", do not modify
*/

const zh = {global: {ZG90LWkxOG57dmFsdWV9: "dot-i18n{value}", "54mb6YC8": "牛逼", "Z29vZG1hbg==": "goodman", "5Zu95bqG5b+r5LmQ": "国庆快乐", "Z2xvYmFsIGkxOG4=": "global i18n"}};

const en = {global: {ZG90LWkxOG57dmFsdWV9: "dot-i18n{value}2", "54mb6YC8": "牛逼2", "Z29vZG1hbg==": "goodman2", "5Zu95bqG5b+r5LmQ": "国庆快乐2", "Z2xvYmFsIGkxOG4=": "global i18n2"}};

module.exports = {zh, en};
