const fs = require("fs-extra");
const i18nStore = require("./i18n-store");
const path = require("path");
const shelljs = require("shelljs");
const babelParser = require("@babel/parser");
const babelTraverse = require("@babel/traverse");
const babelGenerator = require("@babel/generator");
let currentTime = new Date().getTime();

function findI18nTag(node) {
    if ((node.openingElement && node.openingElement.name.name === "i18n") || (node.argument && node.argument.openingElement && node.argument.openingElement.name.name === "i18n")) {
        const openingElement = node.openingElement || node.argument.openingElement;
        console.log(openingElement);
    }
    if ((node.children && node.children.length > 0) || (node.argument && node.argument.children && node.argument.children.length > 0)) {
        const children = node.children || node.argument.children;
        children.forEach((_) => {
            findI18nTag(_);
        });
    }
}

function getLocale() {
    const config = i18nStore.getConfig();
    const source = config.source;
    const languages = config.languages;
    const result = {};
    languages.forEach((_) => {
        result[_] = {};
    });

    shelljs.ls(path.join(process.cwd(), source)).forEach((file) => {
        const filePath = path.join(process.cwd(), `${source}/${file}`);
        const isFile = fs.statSync(filePath).isFile();

        if (isFile) {
            const fileString = fs.readFileSync(filePath, {encoding: "utf-8"});
            if ((file.endsWith("ts") || file.endsWith("tsx")) && (fileString.includes("<i18n") || fileString.includes("i18n("))) {
                const ast = babelParser.parse(fileString, {
                    sourceType: "module",
                    plugins: ["typescript", "jsx"],
                });
                babelTraverse.default(ast, {
                    CallExpression(path) {
                        const i18nContainer = path.get("i18n").container;
                        if (!i18nContainer.callee.object) {
                            const arguments = i18nContainer.arguments;
                            const value = arguments && arguments[0] && arguments[0].value;
                            const language = arguments && arguments[1] && arguments[1].value;
                            const namespace = (arguments && arguments[2] && arguments[2].value) || "global";
                            if (!result[language][namespace]) {
                                result[language][namespace] = {};
                            }
                            if (!Object.values(result[language][namespace]).includes(value)) {
                                result[language][namespace][(currentTime++).toString(16)] = value;
                            }
                        }
                    },
                    ReturnStatement(path) {
                        findI18nTag(path.node);
                    },
                });
                // console.log(babelGenerator.default(ast));
                // console.log(result);
            }
        } else {
            //
        }
    });
}

function createLocale() {
    const config = i18nStore.getConfig();
    const languages = config.languages;
    fs.ensureDirSync(path.join(process.cwd(), "/src/locale"));
    fs.ensureFileSync(path.join(process.cwd(), "/src/locale/index.ts"));
    let indexTemplate = `/*
    Attention: This file is generated by "dot-icon", do not modify
    ref: https://github.com/vocoWone/dot-i18n
*/\n\n`;
    languages.forEach((_) => {
        fs.ensureFileSync(path.join(process.cwd(), `/src/locale/${_}.ts`));
        fs.writeFileSync(path.join(process.cwd(), `/src/locale/${_}.ts`), `export default {}`);
        indexTemplate += `import ${_} from "./${_}";\n`;
    });
    indexTemplate += `\nexport default {${languages.join(", ")}};\n`;
    fs.writeFileSync(path.join(process.cwd(), "/src/locale/index.ts"), indexTemplate);
}

function generate() {
    getLocale();
    createLocale();
}

module.exports = generate;
