import "./initialize";
import fs from "fs-extra";
import * as i18nStore from "./i18n-store";
import path from "path";
import {ls} from "shelljs";
import {parse} from "@babel/parser";
import {JSXElement, CallExpression, JSXIdentifier, JSXAttribute, StringLiteral, JSXText} from "@babel/types";
import babelTraverse, {NodePath} from "@babel/traverse";
import {spawn} from "./kit";

interface MutationResultOptions{
    language?:string;
    namespace?:string;
    value?:string;
}

let result = {};
let currentTime = new Date().getTime();

function mutationResult(options:MutationResultOptions){
    const {language="zh",namespace="global",value} = options
    if (!result[language]) {
        result[language] = {};
    }
    if (!result[language][namespace]) {
        result[language][namespace] = {};
    }
    if (value && !Object.values(result[language][namespace]).includes(value)) {
        result[language][namespace][(currentTime++).toString(16)] = value;
    }
}

function analyzeLocale(baseUrl: string, languages: string[]) {
    ls(path.join(process.cwd(), baseUrl)).forEach((file) => {
        const filePath = path.join(process.cwd(), `${baseUrl}/${file}`);
        const isFile = fs.statSync(filePath).isFile();
        if (isFile) {
            const fileString = fs.readFileSync(filePath, {encoding: "utf-8"});
            if ((file.endsWith("ts") || file.endsWith("tsx")) && (fileString.includes("<i18n") || fileString.includes("i18n("))) {
                const ast = parse(fileString, {
                    sourceType: "module",
                    plugins: ["typescript", "jsx"],
                });
                babelTraverse(ast, {
                    CallExpression(path: NodePath<CallExpression>) {
                        const i18nContainer = (path.get("i18n") as NodePath<CallExpression>).container as i18nStore.ASTContainer;
                        if (!i18nContainer.callee.object && i18nContainer.callee.name === "i18n") {
                            const containerArguments = i18nContainer.arguments;
                            const value = containerArguments?.[0]?.value;
                            const language = languages?.[0];
                            const namespace = containerArguments?.[2]?.value;
                            mutationResult({language,namespace,value})
                        }
                    },
                    JSXElement(path: NodePath<JSXElement>) {
                        if ((path.node.openingElement?.name as JSXIdentifier)?.name === "i18n") {
                            const jsxNode = path.node;
                            const openingElement = jsxNode.openingElement;
                            const attributes = openingElement.attributes as JSXAttribute[];
                            const namespaceAttribute = attributes.find((_) => _.name.name === "namespace");
                            const namespace = (namespaceAttribute?.value as StringLiteral)?.value;
                            if (jsxNode.children.length === 1) {
                                const language = languages?.[0];
                                const value = (jsxNode.children[0] as JSXText).value;
                                mutationResult({language,namespace,value})
                            }
                        }
                    },
                });
            }
        } else {
            analyzeLocale(`${baseUrl}/${file}`, languages);
        }
    });
}

function generateLocale(config: i18nStore.Config,languages:string[]) {
    const outDir = config.outDir || i18nStore.defaultConfig.outDir;
    fs.ensureDirSync(path.join(process.cwd(), outDir));
    fs.ensureFileSync(path.join(process.cwd(), `${outDir}/index.ts`));
    let indexTemplate = `/*
    Attention: This file is generated by "dot-icon", do not modify
    ref: https://github.com/vocoWone/dot-i18n
*/\n\n`;
    languages.forEach((_) => {
        fs.ensureFileSync(path.join(process.cwd(), `${outDir}/${_}.ts`));
        fs.writeFileSync(path.join(process.cwd(), `${outDir}/${_}.ts`), `export default ${JSON.stringify(result?.[_]||{})};\n`);
        indexTemplate += `import ${_} from "./${_}";\n`;
    });
    indexTemplate += `\nexport default {${languages.join(", ")}};\n`;
    fs.writeFileSync(path.join(process.cwd(), `${outDir}/index.ts`), indexTemplate);

    const prettierConfig = config.prettierConfig;
    if (prettierConfig) {
        spawn("prettier", ["--config", path.join(process.cwd(), prettierConfig), "--write", path.join(process.cwd(), outDir + "/*")]);
    }
}

function generate() {
    const allLocales = i18nStore.getLocales();
    if (allLocales instanceof Object) {
        result = {...allLocales};
    }
    const config = i18nStore.getConfig();
    const languages = config?.languages || i18nStore.defaultConfig.languages;
    const baseUrl = config?.baseUrl || i18nStore.defaultConfig.baseUrl;

    analyzeLocale(baseUrl, languages);
    generateLocale(config,languages);
}

generate();
